name: Terraform AKS Update

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0  # Set the version you are using (or the latest)

    - name: Cache Terraform providers
      uses: actions/cache@v3  # Updated to v3
      with:
        path: ~/.terraform.d/plugins
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Set up Azure credentials
      uses: azure/setup-azurecli@v1
      with:
        azure-cli-version: '2.31.0'  # Specify the Azure CLI version
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
